# Generated by Django 3.2.14 on 2022-07-25 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='proposal/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plagiarism_percentage', models.FloatField(default=0)),
                ('dosen', models.ManyToManyField(related_name='dosen', to=settings.AUTH_USER_MODEL)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
