# Generated by Django 3.2.14 on 2022-07-25 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='mahasiswa',
        ),
        migrations.AddField(
            model_name='proposal',
            name='mahasiswa',
            field=models.ManyToManyField(related_name='mahasiswa', to=settings.AUTH_USER_MODEL),
        ),
    ]
