# Generated by Django 3.2.14 on 2022-10-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20220725_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
