# Generated by Django 3.2.14 on 2022-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_proposal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(max_length=300, upload_to='proposal/'),
        ),
    ]
